-- Add missing columns to products table

ALTER TABLE products
ADD COLUMN IF NOT EXISTS min_stock NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'product',
ADD COLUMN IF NOT EXISTS sold NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS revenue NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS discount NUMERIC(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_type TEXT DEFAULT 'percent',
ADD COLUMN IF NOT EXISTS is_unlimited BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS purchase_unit TEXT,
ADD COLUMN IF NOT EXISTS conversion_to_unit NUMERIC(15, 2),
ADD COLUMN IF NOT EXISTS weight NUMERIC(15, 2),
ADD COLUMN IF NOT EXISTS rack_location TEXT;
